
spring:
    h2:
      console:
          enabled: true
    datasource:
        url: jdbc:h2:mem:pilotos
        username: sa
#        password: password
        driverClassName: org.h2.Driver
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
#        hibernate:
#           ddl-auto: none
#        properties:
#            hibernate:
#                default_schema: dbo
    flyway:
        enabled: true
        baseline-on-migrate: true

