
spring:
    h2:
      console:
          enabled: true
    datasource:
        url: jdbc:h2:mem:dbpilotos
        username: sa
#        password: password
        driverClassName: org.h2.Driver
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        properties:
            hibernate:
                default_schema: pilotos
    flyway:
        enabled: true
        baseline-on-migrate: true
        table: flyway_schema_pilotos
        default-schema: pilotos

