CREATE SCHEMA IF NOT EXISTS pilotos;

CREATE SEQUENCE pilotos.PILOTO_SQ
    START WITH 1
  INCREMENT BY 1
  MINVALUE 1;

CREATE SEQUENCE pilotos.HABILIDAD_PILOTO_SQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1;

CREATE SEQUENCE pilotos.HABILIDAD_SQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1;

CREATE TABLE pilotos.PILOTO (
    SQ_PILOTO INT NOT NULL
        DEFAULT (NEXT VALUE FOR pilotos.PILOTO_SQ),
    TIPO_REGISTRO NVARCHAR(25),
    FECHA_CREACION_REGISTRO TIMESTAMP,
    CODIGO_A3 NVARCHAR(3),
    NOMBRE NVARCHAR(255),
    FECHA_NACIMIENTO DATE,
        PRIMARY KEY (SQ_PILOTO)
    );

CREATE TABLE pilotos.HABILIDAD (
    SQ_HABILIDAD INT NOT NULL
       DEFAULT (NEXT VALUE FOR pilotos.HABILIDAD_SQ),
    CODIGO NVARCHAR(10),
    DESCRIPCION nvarchar(255),
        PRIMARY KEY (SQ_HABILIDAD)
);

CREATE TABLE pilotos.HABILIDAD_PILOTO (
    SQ_HABILIDAD_PILOTO INT NOT NULL
      DEFAULT (NEXT VALUE FOR pilotos.HABILIDAD_PILOTO_SQ),
    TIPO_REGISTRO NVARCHAR(25),
    FECHA_CREACION_REGISTRO TIMESTAMP,
    CODIGO_A3_PILOTO  NVARCHAR(3) NOT NULL,
    SQ_HABILIDAD INT NOT NULL,
    CANTIDAD INT DEFAULT 0,
        PRIMARY KEY (SQ_HABILIDAD_PILOTO),
--         FOREIGN KEY (CODIGO_A3_PILOTO) REFERENCES PILOTO(CODIGO_A3),
        FOREIGN KEY (SQ_HABILIDAD) REFERENCES HABILIDAD(SQ_HABILIDAD)
);

CREATE TABLE pilotos.SINCRONIZACION (
    TIPO_SINCRONIZACION NVARCHAR(12) NOT NULL,
    FECHA_ULTIMA_SINCRONIZACION TIMESTAMP NOT NULL,
    PRIMARY KEY (TIPO_SINCRONIZACION)
);

