INSERT INTO HABILIDAD VALUES (1, 'SALIDA', 'DESTREZA EN LA MANIOBRA DE SALIDA');
INSERT INTO HABILIDAD VALUES (2, 'MOJADO', 'DESTREZA DE CONDUCCIOIN SOBRE MOJADO');
INSERT INTO HABILIDAD VALUES (3, 'SECO', 'DESTREZA DE CONDUCCION SOBRE SECO');
INSERT INTO HABILIDAD VALUES (4, 'TRAFICO', 'DESTREZA DE CONDUCCION ESTANDO EN TRAFICO');

INSERT INTO PILOTO (TIPO_REGISTRO, FECHA_CREACION_REGISTRO, CODIGO_A3, NOMBRE, FECHA_NACIMIENTO) VALUES ('ALTA', CURRENT_TIMESTAMP, 'ALO', 'FERNANDO ALONSO', '1981-12-31');

INSERT INTO HABILIDAD_PILOTO (TIPO_REGISTRO, FECHA_CREACION_REGISTRO, SQ_PILOTO, SQ_HABILIDAD, CANTIDAD)
VALUES ('ALTA', CURRENT_TIMESTAMP, 1, 1, 90);
INSERT INTO HABILIDAD_PILOTO (TIPO_REGISTRO, FECHA_CREACION_REGISTRO, SQ_PILOTO, SQ_HABILIDAD, CANTIDAD)
VALUES ('ALTA', CURRENT_TIMESTAMP, 1, 2, 80);
INSERT INTO HABILIDAD_PILOTO (TIPO_REGISTRO, FECHA_CREACION_REGISTRO, SQ_PILOTO, SQ_HABILIDAD, CANTIDAD)
VALUES ('ALTA', CURRENT_TIMESTAMP, 1, 3, 95);
INSERT INTO HABILIDAD_PILOTO (TIPO_REGISTRO, FECHA_CREACION_REGISTRO, SQ_PILOTO, SQ_HABILIDAD, CANTIDAD)
VALUES ('ALTA', CURRENT_TIMESTAMP, 1, 4, 90);
