INSERT INTO pilotos.HABILIDAD VALUES (1, 'SALIDA', 'DESTREZA EN LA MANIOBRA DE SALIDA');
INSERT INTO pilotos.HABILIDAD VALUES (2, 'MOJADO', 'DESTREZA DE CONDUCCIOIN SOBRE MOJADO');
INSERT INTO pilotos.HABILIDAD VALUES (3, 'SECO', 'DESTREZA DE CONDUCCION SOBRE SECO');
INSERT INTO pilotos.HABILIDAD VALUES (4, 'TRAFICO', 'DESTREZA DE CONDUCCION ESTANDO EN TRAFICO');

INSERT INTO pilotos.PILOTO (TIPO_REGISTRO, FECHA_CREACION_REGISTRO, CODIGO_A3, NOMBRE, FECHA_NACIMIENTO) VALUES ('ALTA_PILOTO', CURRENT_TIMESTAMP, 'ALO', 'FERNANDO ALONSO', '1981-12-31');

INSERT INTO pilotos.HABILIDAD_PILOTO (TIPO_REGISTRO, FECHA_CREACION_REGISTRO, CODIGO_A3_PILOTO, SQ_HABILIDAD, CANTIDAD)
VALUES ('ALTA_HABILIDAD', CURRENT_TIMESTAMP, 'ALO', 1, 90);
INSERT INTO pilotos.HABILIDAD_PILOTO (TIPO_REGISTRO, FECHA_CREACION_REGISTRO, CODIGO_A3_PILOTO, SQ_HABILIDAD, CANTIDAD)
VALUES ('ALTA_HABILIDAD', CURRENT_TIMESTAMP, 'ALO', 2, 80);
INSERT INTO pilotos.HABILIDAD_PILOTO (TIPO_REGISTRO, FECHA_CREACION_REGISTRO, CODIGO_A3_PILOTO, SQ_HABILIDAD, CANTIDAD)
VALUES ('ALTA_HABILIDAD', CURRENT_TIMESTAMP, 'ALO', 3, 95);
INSERT INTO pilotos.HABILIDAD_PILOTO (TIPO_REGISTRO, FECHA_CREACION_REGISTRO, CODIGO_A3_PILOTO, SQ_HABILIDAD, CANTIDAD)
VALUES ('ALTA_HABILIDAD', CURRENT_TIMESTAMP, 'ALO', 4, 90);
